version: '3.7'

services:
  app:
    container_name: app
    image: lex/warmup:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
#      - "php_data:/var/www"
      - "${PWD}/docker/php/php-fpm.d:/usr/local/etc/php-fpm.d"
      - "${PWD}/docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf"
      - "${PWD}/docker/php/pear.conf:/usr/local/etc/pear.conf"
      - "${PWD}/docker/.bashrc:/root/.bashrc"
    environment:
      SHELL: /bin/bash

  www:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - app
    container_name: web
    volumes:
      - "${PWD}/docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "${PWD}/docker/nginx/default:/etc/nginx/sites-available/default"
        
volumes:
  php_data: {}
